### ISSUE TITLE
修改插件配置文件结构

### ISSUE THREAD

**Issue by YufiriaMazenta** [YufiriaMazenta/Craftorithm#33]
以添加更多扩展功能

**Comment by YufiriaMazenta** [comment]
可能需要修改为，一个文件代表一个配方组，文件内格式如下
```yaml
type:
result:
recipe1:
  type:
  result:
  ingredient:
  其他特殊键:
recipe2:
  type:
  其他键:
```
几个通用顶层key，当下级配方没有设定时，使用顶层值
