### ISSUE TITLE
MMOItems物品在配方中随机数值无法合成后更新 & 在cookie类型配方中输出物为MMOItems水桶类型物品导致的错误

### ISSUE THREAD

**Issue by jiuwu02** [YufiriaMazenta/Craftorithm#60]
### Describe the bug | 描述你遇到的bug

在工作台配方中创建了 输出物品 带有随机范围数值的物品在合成的时候一直都为固定数值。
理想修复结果：合成后更新范围数值

当cookie类型的配方中 输出物品 为MMOItems插件创建的水桶类型物品时，会导致输出结果不为输出物品
理想修复结果：功能正常工作

### Steps to reproduce the bug | 复现此Bug的步骤

创建一个带有范围数值的MMOItems物品

`MMOItems/item/material.yml`:
```
精炼铁锭:
  base:
    material: IRON_INGOT
    enchants:
      unbreaking: 1.0
    hide-enchants: true
    name: <#434B4D>精炼铁锭
    lore:
    - '&7普铁再熔提纯，坚硬耐用，铸造精'
    - '&7良器物之选材'
    disable-interaction: true
    disable-enchanting: true
    disable-repairing: true
```
`MMOItems/item/armor.yml`:
```
精炼铁头盔:
  base:
    material: IRON_HELMET
    name: <#434B4D>精炼铁头盔
    max-durability:
      min: 250
      max: 300
    fall-damage-reduction:
      min: 2.0
      max: 7.0
    fire-damage-reduction:
      min: 2.0
      max: 7.0
    armor: 3.0
```
创建配方 refined_iron_helmet.yml:
```
type: shaped
shape:
  - def
  - g i
source:
  d: mmoitems:MATERIAL:精炼铁锭
  e: mmoitems:MATERIAL:精炼铁锭
  f: mmoitems:MATERIAL:精炼铁锭
  g: mmoitems:MATERIAL:精炼铁锭
  i: mmoitems:MATERIAL:精炼铁锭
unlock: true
result: mmoitems:ARMOR:精炼铁头盔 1
```
重载插件，合成该物品，输出结果一直为固定数值

============================================================

首先添加两个MMOItems材料物品
`MMOItems/item/material.yml`:
```
精炼铁锭:
  base:
    material: IRON_INGOT
    enchants:
      unbreaking: 1.0
    hide-enchants: true
    name: <#434B4D>精炼铁锭
    lore:
    - '&7普铁再熔提纯，坚硬耐用，铸造精'
    - '&7良器物之选材'
    disable-interaction: true
    disable-enchanting: true
    disable-repairing: true
精炼铁水:
  base:
    material: WATER_BUCKET
    name: <#434B4D>精炼铁水
    lore:
    - '&7精炼铁水由精炼铁锭在高温下熔化'
    - '&7形成，其高纯度和流动性使其成为'
    - '&7打造优质金属器物的理想原材料'
    disable-interaction: true
    disable-enchanting: true
    disable-repairing: true
```
然后创建cookie配方
`refined_hot_metal.yml`
```
type: cooking
result: mmoitems:MATERIAL:精炼铁水 1
multiple: true
unlock: true
source:
- item: mmoitems:MATERIAL:精炼铁锭
  block: furnace
  time: 400
  exp: 0.0
- item: mmoitems:MATERIAL:精炼铁锭
  block: blast_furnace
  time: 400
  exp: 0.0
```
重载插件，测试结果：在高炉中合成的输出物结果为 输入物

### Server version | 服务器版本

![image](https://github.com/YufiriaMazenta/Craftorithm/assets/107833020/67315446-d084-4f42-bd6c-51ebedef23ba)

### Craftorithm Version | Craftorithm的版本

![image](https://github.com/YufiriaMazenta/Craftorithm/assets/107833020/db4421e9-9837-4905-81e4-dcf2ff7250d0)
