### ISSUE TITLE
合成配方匹對應要更準確&自動合成器可突破限制

### ISSUE THREAD

**Issue by tygh89071388** [YufiriaMazenta/Craftorithm#93]
### Describe the bug | 描述你遇到的bug

```
type: shaped
shape:
- aaa
- bbb
- bbb
source:
  a: mmoitems:MATERIAL:魔法粉塵
  b: minecraft:glowstone_dust
unlock: false
result: mmoitems:MATERIAL:魔法粉磚 1

```

設定為 minecraft:glowstone_dust
時應該只能匹配 無name無lore的物品 而不是物品類型是glowstone_dust就匹配

會導致9格都放滿 mmoitems:MATERIAL:魔法粉塵 時依然可以正常合成 mmoitems:MATERIAL:魔法粉磚
雖然可透過config.yml中的 lore_cannot_craft: .*RPG資訊.* 去限制 但同時也會直接限制mmoitems用於其他合成的功能

以及即使使用 lore_cannot_craft: .*RPG資訊.* 進行限制 但在1.21更新中的合成器(crafter)依然可突破限制去進行合成

### Steps to reproduce the bug | 复现此Bug的步骤

如上

### Server version | 服务器版本

 Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Craftorithm Version | Craftorithm的版本

Plugin version: 1.10.17-20250121
